version: "3"
services:
  argo-tokens:
    image: netfloex/argo_token_api
    container_name: argo-tokens
    environment:
      TOKEN: "secret"
    # ports:
    # - 2000:3000
    volumes:
      - ./data:/app/data

networks:
  default:
    external:
      name: nginx
